apiVersion: database.aws.crossplane.io/v1beta1
kind: DBSubnetGroup
metadata:
  name: $(EKS_CLUSTER_NAME)-catalog-crossplane
  labels:
    app.kubernetes.io/created-by: eks-workshop
spec:
  forProvider:
    region: $(AWS_REGION)
    description: DBSubnet group
    subnetIds:
    - $(VPC_PRIVATE_SUBNET_ID_1)
    - $(VPC_PRIVATE_SUBNET_ID_2)
    - $(VPC_PRIVATE_SUBNET_ID_3)
    tags:
    - key: created-by
      value: eks-workshop-v2
    - key: env
      value: $(EKS_CLUSTER_NAME)
    - key: managed-by
      value: crossplane
  providerConfigRef:
    name: default
