name: E2E Tests - Parallel

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: [ fundamentals, security, autoscaling, observability, automation, networking ]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install utilities
      run: |
        sudo apt install -y gettext

        mkdir -p ${HOME}/.local/bin
        wget https://github.com/jckuester/awsweeper/releases/download/v0.12.0/awsweeper_0.12.0_linux_amd64.tar.gz
        tar zxf awsweeper_0.12.0_linux_amd64.tar.gz
        mv awsweeper_0.12.0_linux_amd64/awsweeper ${HOME}/.local/bin

        wget https://github.com/eksctl-io/eksctl/releases/download/v0.150.0/eksctl_Linux_amd64.tar.gz
        tar zxf eksctl_Linux_amd64.tar.gz
        mv eksctl ${HOME}/.local/bin

        chmod +x ${HOME}/.local/bin/*

        echo "${HOME}/.local/bin" >> $GITHUB_PATH
    - name: Get AWS credentials
      uses: aws-actions/configure-aws-credentials@v1.6.1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-duration-seconds: 3600
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: GithubActionsSession
    - name: Set cluster ID
      env:
        AWS_REGION: "${{ secrets.AWS_REGION }}"
      run: |
        RANDOM_ID=$(echo $RANDOM | md5sum | head -c 8; echo)
        CLUSTER_ID="ci-${RANDOM_ID}"

        echo "Cluster ID is ${CLUSTER_ID}"

        echo "CLUSTER_ID=$CLUSTER_ID" >> $GITHUB_ENV
        echo "AWS_DEFAULT_REGION=$AWS_REGION" >> $GITHUB_ENV
    - name: Create infrastructure
      id: create-infrastructure
      env:
        AWS_REGION: "${{ secrets.AWS_REGION }}"
      run: |
        make create-infrastructure environment="$CLUSTER_ID"
    - name: Refresh AWS credentials
      if: always()
      uses: aws-actions/configure-aws-credentials@v1.6.1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-duration-seconds: 3600
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: GithubActionsSession
    - name: Run tests - Introduction
      env:
        DOCKER_BUILDKIT: 1
        DEV_MODE: 1
      run: |
        make test environment="$CLUSTER_ID" module="introduction"
    - name: Run tests
      env:
        DOCKER_BUILDKIT: 1
        DEV_MODE: 1
      run: |
        make test environment="$CLUSTER_ID" module="${{ matrix.module }}"
    - name: Run tests - Cleanup
      if: always()
      env:
        DOCKER_BUILDKIT: 1
        DEV_MODE: 1
      run: |
        make test environment="$CLUSTER_ID" module="cleanup"
    - name: Refresh AWS credentials
      if: always()
      uses: aws-actions/configure-aws-credentials@v1.6.1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-duration-seconds: 3600
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: GithubActionsSession
    - name: Cleanup environment
      if: always()
      env:
        AWS_REGION: "${{ secrets.AWS_REGION }}"
      run: |
        export CLEANUP_ENVIRONMENT_NAME="$CLUSTER_ID"
        
        envsubst < hack/lib/filter.yml > filter.yml

        cat filter.yml

        awsweeper --force filter.yml

        make destroy-infrastructure environment="$CLUSTER_ID"
